export const lightTheme = {
  colors: {
    primary: '#0066cc',
    primaryLight: '#e6f0ff',
    secondary: '#ff9500',
    background: '#f9f9f9',
    cardBackground: '#ffffff',
    text: '#333333',
    textSecondary: '#666666',
    border: '#e0e0e0',
    success: '#4caf50',
    error: '#f44336',
    warning: '#ff9800',
    info: '#2196f3',
    codeBackground: '#f5f5f5',
    codeText: '#333333',
    buttonDisabled: '#E2E8F0',
    buttonTextDisabled: '#94A3B8',
    categoryButton: '#F1F5F9',
    progressBar: '#E2E8F0',
    progressFill: '#2563EB',
    shadow: 'rgba(0, 0, 0, 0.05)',
    gradient: {
      start: '#2563EB',
      end: '#3B82F6',
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 6,
    md: 12,
    lg: 16,
    xl: 24,
  },
  typography: {
    h1: {
      fontSize: 32,
      fontWeight: 'bold',
      letterSpacing: -0.5,
    },
    h2: {
      fontSize: 28,
      fontWeight: 'bold',
      letterSpacing: -0.3,
    },
    h3: {
      fontSize: 24,
      fontWeight: '600',
    },
    body: {
      fontSize: 16,
      lineHeight: 24,
    },
    caption: {
      fontSize: 14,
      lineHeight: 20,
    },
    code: {
      fontSize: 14,
      fontFamily: 'monospace',
      lineHeight: 20,
    },
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 1,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 3,
      elevation: 2,
    },
    large: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 5,
      elevation: 4,
    },
  },
};

export const darkTheme = {
  colors: {
    primary: '#3399ff',
    primaryLight: '#1a2d40',
    secondary: '#ff9500',
    background: '#121212',
    cardBackground: '#1e1e1e',
    text: '#f0f0f0',
    textSecondary: '#b0b0b0',
    border: '#333333',
    success: '#4caf50',
    error: '#f44336',
    warning: '#ff9800',
    info: '#2196f3',
    codeBackground: '#2d2d2d',
    codeText: '#e0e0e0',
    buttonDisabled: '#334155',
    buttonTextDisabled: '#64748B',
    categoryButton: '#1E293B',
    progressBar: '#334155',
    progressFill: '#3B82F6',
    shadow: 'rgba(0, 0, 0, 0.3)',
    gradient: {
      start: '#3B82F6',
      end: '#60A5FA',
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 6,
    md: 12,
    lg: 16,
    xl: 24,
  },
  typography: {
    h1: {
      fontSize: 32,
      fontWeight: 'bold',
      letterSpacing: -0.5,
    },
    h2: {
      fontSize: 28,
      fontWeight: 'bold',
      letterSpacing: -0.3,
    },
    h3: {
      fontSize: 24,
      fontWeight: '600',
    },
    body: {
      fontSize: 16,
      lineHeight: 24,
    },
    caption: {
      fontSize: 14,
      lineHeight: 20,
    },
    code: {
      fontSize: 14,
      fontFamily: 'monospace',
      lineHeight: 20,
    },
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 1,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.4,
      shadowRadius: 3,
      elevation: 2,
    },
    large: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.5,
      shadowRadius: 5,
      elevation: 4,
    },
  },
}; 